---
title: "varroa karyotyping"
author: "Nurit Eliash"
date: "4/7/2022"
output:
  html_document:
    code_folding: hide
    theme: cerulean
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: yes
      df_print: paged
---
<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries
```{r libraries, echo=TRUE, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(ggthemes)
library(stats) 
library(moments)
library(grid)
library(formattable)
library(gridExtra)
library(ggsignif)
library(hrbrthemes)
library(plotrix)
library(rstatix)
library(car)
library(plotly)
library(plyr)

```

## Load data
```{r echo=TRUE, message=FALSE, warning=FALSE}
dat <- read.csv("/Users/nuriteliash/Documents/GitHub/varroa karyotyping/karyo_varroa.csv")
summary(dat)
```

sasha suggested plot (17/5/2022):
```{r}
#Sasha Mikheyev
dat %>% ggplot(aes(chromo_number, cell_perc, group=ID, color = sex) ) + 
  geom_line(alpha=.3) + 
  stat_smooth(se=F, method="gam", aes(group=sex)) + 
  theme_bw() + 
  geom_vline(xintercept = 7, color = "blue") +
  geom_vline(xintercept = 14, color = "red") +
 theme_classic2() +
ggtitle("Distribution of chromosome count") +
        xlab("Number of chromosomes per cell") +
        ylab("Percentage of cells per sample")
```

i tried different plots to visualize the distribution:
```{r echo=TRUE, message=FALSE, warning=FALSE}
# mean of proportion, all samples in the same plot
ggplot(dat, aes(x=as.factor(chromo_number), y= cell_perc, fill = sex)) + 
  geom_boxplot( ) +
  scale_fill_brewer(palette = "Set1") +
  theme(legend.position="right") +
  ggtitle("Distribution of chromosome count") +
        xlab("Number of chromosomes per cell") +
        ylab("Percentage of cells per sample")

# a bar plot
ggplot(dat, aes(x=as.factor(chromo_number), y= cell_perc,group = ID ,fill = sex)) + 
  geom_bar(position = "dodge" , stat="identity") +
scale_fill_brewer(palette = "Set1") +
  theme(legend.position="right") +
  theme_linedraw() +
ggtitle("Distribution of chromosome count") +
        xlab("Number of chromosomes per cell") +
        ylab("Percentage of cells per sample")

# a line plot (less appropriate, as the chromosome number is NOT a continuos value, but at least the different samples are visible)
p <- ggplot(dat, aes(x=as.factor(chromo_number), y= cell_perc,group = ID ,color = sex)) + 
  geom_line(position = "dodge" , stat="identity") +
scale_fill_brewer(palette = "Set1") +
  theme(legend.position="right") +
 theme_classic2() +
ggtitle("Distribution of chromosome count") +
        xlab("Number of chromosomes per cell") +
        ylab("Percentage of cells per sample")

ggplotly(p, tooltip = "ID")

# facet each sample
ggplot(dat, aes(x=as.factor(chromo_number), y= cell_perc,group = ID ,fill = sex)) + 
  geom_bar(position = "dodge" , stat="identity") +
    facet_wrap( ~ ID) +
scale_fill_brewer(palette = "Set1") +
  theme(legend.position="right") +
  theme_linedraw() +
ggtitle("Distribution of chromosome count") +
        xlab("Number of chromosomes per cell") +
        ylab("Percentage of cells per sample")

```

