---
title: "Karyotyping-revised"
date: "April 2025"
output:
  html_document:
    code_folding: hide
    theme: cerulean
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: yes
      df_print: paged
editor_options: 
  chunk_output_type: console
---

```{=html}
<style type="text/css">
  body{
  font-size: 12pt;
}
</style>
```

```{r load library, echo = T, results = 'hide', message=FALSE, warning=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggsignif)
knitr::opts_chunk$set(echo = TRUE)
```

```{r load data- karyptyping, message=FALSE, warning=FALSE}
dat <- read_csv("/Users/nuriteliash/Documents/GitHub/varroa-karyotyping/data/karyo_varroa_sasha.csv", col_types = "cccnnn")
```


```{r karyotyping-males-females}
dat_means <- dat %>% group_by(ID) %>% 
    reframe(
        chroms = sum(cell_count * chromo_number) / sum(cell_count), 
        count = sum(cell_count), 
        sd = sqrt(sum(cell_count * (chromo_number - chroms)^2) / sum(cell_count)), 
        sem = sd / sqrt(count), 
        ci_lower = chroms - qt(0.975, df = count - 1) * sem, 
        ci_upper = chroms + qt(0.975, df = count - 1) * sem, 
        sex = Sex[1])

dat_means %>%
ggplot(aes(x = sex, y = chroms, color = sex, size = count)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), size = 1, width = 0.05, position=position_jitter(width=0.2)) + 
  scale_color_manual(values = c("Male" = "blue", "Female" = "#E31C79")) +  # Custom colors
  scale_size_continuous(range = c(3, 10)) +  # Custom size range
  geom_hline(yintercept = 7, color = "blue") + 
  geom_hline(yintercept = 14, color = "#E31C79") + 
  theme_bw() + 
  ylab("Chromosome count") + 
  geom_signif(comparisons = list(c("Male", "Female")), map_signif_level = TRUE, test = "wilcox.test", color = "black") + 
  scale_y_continuous(breaks = scales::breaks_pretty()) + 
  theme(legend.position = "bottom") + 
  guides(color = "none") +  
  labs(size = "Number of cells examined per individual") + 
  xlab("Sex")
#ggsave("karyptype.pdf", heigh=5, width=5)
```

Do males have significantly less chromosomes than the diploid number of 14?
```{r karyotyping-stats}
filter(dat_means, sex == "Male") %>% pull(chroms) %>% t.test(., mu = 14)
```
