---
title: "Karyotyping and RNA-seq"
format: html
---

```{r}
library(tidyverse)
library(ggsignif)
dat <- read_csv("data/karyo_varroa.csv", col_types = "cccnnn")
rna_dat <- read_csv("data/rna-seq.csv")
```


```{r}
dat_means <- dat %>% group_by(ID) %>% 
    reframe(
        chroms = sum(cell_count * chromo_number) / sum(cell_count), 
        count = sum(cell_count), 
        sd = sqrt(sum(cell_count * (chromo_number - chroms)^2) / sum(cell_count)), 
        sem = sd / sqrt(count), 
        ci_lower = chroms - qt(0.975, df = count - 1) * sem, 
        ci_upper = chroms + qt(0.975, df = count - 1) * sem, 
        sex = Sex[1])

dat_means %>%
ggplot(aes(x = sex, y = chroms, color = sex, size = count)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), size = 1, width = 0.05, position=position_jitter(width=0.2)) + 
  scale_color_manual(values = c("male" = "blue", "female" = "#E31C79")) +  # Custom colors
  scale_size_continuous(range = c(3, 10)) +  # Custom size range
  geom_hline(yintercept = 7, color = "blue") + 
  geom_hline(yintercept = 14, color = "#E31C79") + 
  theme_bw() + 
  ylab("Chromosome count") + 
  geom_signif(comparisons = list(c("male", "female")), map_signif_level = TRUE, test = "wilcox.test", color = "black") + 
  scale_y_continuous(breaks = scales::breaks_pretty()) + 
  theme(legend.position = "bottom") + 
  guides(color = "none") +  
  labs(size = "Number of cells examined per individual") + 
  xlab("Sex")
  
ggsave("karyptype.pdf", heigh=5, width=5)
```

Do males have significantly less chromosomes than the diploid number of 14?
```{r}
filter(dat_means, sex == "male") %>% pull(chroms) %>% t.test(., mu = 14)
```


# RNA-seq

```{r}
rna_dat_summary <- rna_dat %>%
  group_by(family, sex) %>%
  summarize(
    het_prop = sum(het) / sum(het + homo),  # Proportion of heterozygous
    count = sum(het + homo),                # Total trials
    sem = sqrt((het_prop * (1 - het_prop)) / count),  # Standard error of the mean
    ci_lower = het_prop - qt(0.975, df = count - 1) * sem,  # Lower confidence interval
    ci_upper = het_prop + qt(0.975, df = count - 1) * sem   # Upper confidence interval
  )

# Plot the data
rna_dat_summary %>%
  ggplot(aes(x = sex, y = het_prop, colour = sex, group = family)) +
  geom_line(position = position_dodge(width = 0.5), colour = "black") +  
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), size = 1, position = position_dodge(width = 0.5)) +
  theme_bw() +
  
  ylab("Proportion of heterozygous sites") +
  xlab("Sex") +
  theme(legend.position = "bottom") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_x_discrete(labels = c("m" = "Male", "f" = "Female")) + scale_color_manual(values = c("m" = "blue", "f" = "#E31C79")) 
```
